apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskify-backend-blue
  namespace: taskify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskify-backend
      color: blue
  template:
    metadata:
      labels:
        app: taskify-backend
        color: blue
    spec:
      containers:
        - name: backend
          image: myregtf.azurecr.io/taskify-backend:${IMAGE_TAG}
          ports:
            - containerPort: 5000
          env:
            - name: DB_SERVER
              value: mssql
            - name: DB_PORT
              value: "1433"
            - name: DB_USER          # use SA for now
              value: "sa"
            - name: DB_PASSWORD      # SA password from secret
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_PASSWORD
            - name: DB_DATABASE      # use master until you create taskify_db + user
              value: "master"
            - name: PORT
              value: "5000"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskify-backend-green
  namespace: taskify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskify-backend
      color: green
  template:
    metadata:
      labels:
        app: taskify-backend
        color: green
    spec:
      containers:
        - name: backend
          image: myregtf.azurecr.io/taskify-backend:${IMAGE_TAG}
          ports:
            - containerPort: 5000
          env:
            - name: DB_SERVER
              value: mssql
            - name: DB_PORT
              value: "1433"
            - name: DB_USER
              value: "sa"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_PASSWORD
            - name: DB_DATABASE
              value: "master"
            - name: PORT
              value: "5000"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: taskify-backend
  namespace: taskify
spec:
  type: ClusterIP
  selector:
    app: taskify-backend
    color: blue   # initial live color
  ports:
    - port: 5000
      targetPort: 5000
